### PR TITLE
Enable AllowTopicCreation config in example

### LINKED ISSUE #74: Error when run example in README.md
I run the example in README.md after set the correct `kafkaAddrs`, it has error:
`2016/12/02 18:01:34 cannot create kafka consumer for my-messages:0: unknown topic or partition (3)`

Finally, I find that I need to config the brocker to allow topic creation. I think there is need to set `AllowTopicCreation=true` in the example, otherwise the user need to manually create the topic `my-messages` in advance.

### PR DESCRIPTION
**Pull request by supereagle**
fix #74

### CODE REVIEW

**Comment by supereagle** [comment]
@husio Not sure why the check failed, do you know the reason?

**Comment by husio** [comment]
@supereagle I am no longer contributing to this repository.

From what I can see, tests are failing for `tip` version of the compiler. This should not be a blocker.

**Comment by e-max** [comment]
It looks like they've changed compress/gzip library in go 1.8.   I'll take a look.

**Comment by e-max** [comment]
Yep. They've fixed DataModification field in the header of gzipped data.   It wasn't a good idea to hard code binary results in our test, I guess. :)

**Comment by supereagle** [comment]
@e-max  Could you help to fix the error in tests? Thanks.

**Comment by e-max** [comment]
Yes, sure. I am on it.

**Comment by e-max** [comment]
Master is fixed. Could you please rebase your branch on it?

**Comment by e-max** [comment]
Thanks!

**Pull request merged**
