### PR TITLE
V0.10.0

### PR DESCRIPTION
**Pull request by e-max**

### CODE REVIEW

**Comment by e-max** [comment]
I would like to discuss with Sat the best way to integrate multiversions in current broker implementation.  I've fixed tests and relocated apiversions information in connection structure.

**Comment by satran** [comment]
FYI: I had to rebase to master as the history was quite polluted which meant doing a force push.

**Comment by e-max** [comment]
Yes. Sorry about this. I've decided that it makes sense to rebase this branch on the master because it touches the same pieces of code and it is much easier to rebase it now than to continue to work on it and make painful rebase later.

**Comment by optiomas** [comment]
@e-max Can we close this?

**Comment by e-max** [comment]
Yep, I've already added everything from here in the current driver

**Pull request closed without merging**
