### PR TITLE
randomProducer panics when given empty partitions

### PR DESCRIPTION
**Pull request by basharal**
When producing messages using option AllowTopicCreation, the number of partitions for the topic will be 0 initially causing randomProducer to panic when producing the messages since Intn panics on 0. This fixes the issue

### CODE REVIEW

**Comment by optiopay-backend-helper** [comment]
Pull request seem to be stale, assigning @husio as the responsible developer.

**Comment by husio** [comment]
Can you please add this comment to the code as well?

**Comment by basharal** [comment]
Done

**Comment by husio** [comment]
:+1:

**Pull request merged**
