### PR TITLE
Add ConsumeBatch

### PR DESCRIPTION
**Pull request by zorkian**
This is a more optimized way of getting messages from the consumer, if
you are willing to handle the batches yourself.

### CODE REVIEW

**Comment by zorkian** [comment]
Tentative -- this is for the https://github.com/zorkian/marshal higher level consumer. We want to implement batch functionality for better consumption speed (instead of getting mutexes every message, they can be got every batch).

Thoughts?

**Comment by optiopay-backend-helper** [comment]
Pull request seem to be stale, assigning @PragmaticCypher as the responsible developer.

**Comment by husio** [comment]
I really like the idea. I was thinking about it for a long time, but I could never find proper solution to this because of backward compatibility problem. I cannot accept what you're proposing, because at least we have a lot of code that relies on `Consumer` interface to have only `Consume` method. The functionality is good, but no change can break existing code.

There are several other ways this could be done that I can think of:

* extend `consumer` with `ConsumeBatch` method and add `BatchConsumer` method to `Broker` (not `Client` interface) that will return `consumer` as new `BatchConsumer` interface
* extend `consumer` with `ConsumeBatch` method and always check if returned by broker consumer implements `ConsumeBatch`
* Use channel instead of locking, although this will be way slower and does not make much sense.

I like first solution most, but it's still not completely clear to me what should be `BatchConsumer` interface notation. I would also love to see some benchmarks first, what can be gained by using `BatchConsume` instead of `Consume`

**Comment by husio** [comment]
@zorkian are you going to work on this pull request? If so, no matter what will be final implementation, please provide some benchmarks first to justify the change.
Otherwise I will close the pull request. I spend some time on it doing experimental implementation and thinking how it could be used and I ended up (again) with no good solution.

**Comment by zorkian** [comment]
I will still work on this; was traveling.

I don't yet have a benchmark but will try to pull something together to see whether or not it makes sense.

**Comment by husio** [comment]
No worries, take your time then.

**Comment by alpe** [comment]
I'd like to avoid long living PRs without any updates.  (Rule of thumb: 14 days)
@zorkian when we're closing this, it does not mean rejected. Please feel free reopen it again when you have more data. Thanks for your time and effort!

**Comment by zorkian** [comment]
Yeah, that's a reasonable policy. I haven't found a good test case that proves that batch consumption is flat out faster. Even with the current code we're able to get 50,000 messages per second via our Marshal library given enough partitions claimed and that's faster than it's possible to do useful work.

So, for now, I'm going to abandon the effort. I'll reopen/open something new in the future if I actually come up with something that proves it.

**Pull request closed without merging**
