### PR TITLE
Stop sending requests after finished readRespLoop

### PR DESCRIPTION
**Pull request by dmage**
readRespLoop stops when Kafka broker goes down, but nextIDLoop
continues to work and allows you to send new requests.

But these requests will never get answers.

### CODE REVIEW

**Comment by legionus** [comment]
+1
I got this bug too.

**Comment by husio** [comment]
You are right. I'm just wondering, isn't this patch moving issue to `readRespLoop` instead? What if I will manage to create reader but there will be no response because connection was closed? Will it hang here? https://github.com/optiopay/kafka/pull/13/files#diff-8f8a79f3f89c69a28dd878de98384cf9R96

**Comment by husio** [comment]
I wrote small test, but meanwhile I think there are more issues with connection right now:

* response channel is not always properly closed (easy to fix)
* `nextID` is still returning even after closing (easy to fix)
* it is possible to send message after underlaying `io.ReadWriteCloser` has been closed - this means that new response channel is registered, but response will never arrive (hard to fix)

Here's test case that inspects connection internals to test: 

```go
func TestClosedConnectionWriter(t *testing.T) {
        // create test server with no messages, so that any client connection will
        // be immediately closed
        ln, err := testServer()
        if err != nil {
                t.Fatalf("test server error: %s", err)
        }
        conn, err := newTCPConnection(ln.Addr().String(), time.Second)
        if err != nil {
                t.Fatalf("could not conect to test server: %s", err)
        }

        longBytes := []byte(strings.Repeat("xxxxxxxxxxxxxxxxxxxxxx", 1000))
        req := proto.ProduceReq{
                ClientID:     "test-client",
                RequiredAcks: proto.RequiredAcksAll,
                Timeout:      100,
                Topics: []proto.ProduceReqTopic{
                        proto.ProduceReqTopic{
                                Name: "test-topic",
                                Partitions: []proto.ProduceReqPartition{
                                        proto.ProduceReqPartition{
                                                ID: 0,
                                                Messages: []*proto.Message{
                                                        &proto.Message{Value: longBytes},
                                                },
                                        },
                                },
                        },
                },
        }
        for i := 0; i < 10; i++ {
                if _, err := conn.Produce(&req); err == nil {
                        t.Fatalf("message publishing after closing connection should not be possible")
                }
        }

        // although we produced two requests, because connection is closed, no
        // response channel should be registered
        if len(conn.respc) != 0 {
                t.Fatalf("expected 0 waiting responses, got %d", len(conn.respc))
        }
}
```

**Comment by husio** [comment]
I have created another pull request where I fix some of the problems https://github.com/optiopay/kafka/pull/14

There is still issue of socket failing and connection not closing, but this is covered by broke code - whenever connection dies https://github.com/optiopay/kafka/blob/master/broker.go#L420-L435 is closing it and creating new one.

Does this solve the problem or I'm still missing something here?

**Comment by legionus** [comment]
Problem is not solved. If kafka broker restarts ReadResp will return error. At this moment connection is no longer valid and you need to close it.

**Comment by dmage** [comment]
> https://github.com/optiopay/kafka/pull/13/files#diff-8f8a79f3f89c69a28dd878de98384cf9R96
There is a bigger problem if no one is listening on the other side of the channel. We'll get response only after successful WriteTo. So no, will not hang here.

You can not resolve this problem on the broker side, because the connection hangs and does not return errors.

PR #14 doesn't resolve my problems because WriteTo always successful on my installation. After EOF from ReadResp I get success from WriteTo and wait forever response from channel. I have no idea why write successful, but so it is.

**Comment by dmage** [comment]
I added test case. To run it on parent commit you should use `go test -timeout 5s ./...` or it hangs forever.

**Comment by husio** [comment]
I'm having problems to reproduce this issue. I've run the test several times (I even increased the timeout to several seconds) and it's always passing.

Do I understand correctly, that this test should fail in version 537ccf25c1a1d9d83590ea7992e83e0b2fe11745  because of the bug? Can you tell me which system and Go version are you using?

The tests are passing on travis as well (it's failing for other reasons) https://travis-ci.org/optiopay/kafka/jobs/68508985

**Comment by dmage** [comment]
This test should fail without changes in this pull request.

**Comment by dmage** [comment]
To make it clear, I've updated the patch. Commit 82cad65 adds broken test, and 95ce31e fixes it.

**Comment by husio** [comment]
@dmage I made some progress in pull request #14 I also cherry picked your tests commit there. I think it is also fixing the problem of connection goroutines. Can you have a look and confirm?

I have created test with real kafka cluster and this helped to fix few more bugs. Sadly, travis does not provide docker so they need to be run locally.

**Comment by legionus** [comment]
You fixed the bug. But you call c.rw.Close() only in Close method. I see connections in the CLOSE_WAIT state when I stop one of the processes kafka.

**Comment by husio** [comment]
> You fixed the bug. But you call c.rw.Close() only in Close method. I see connections in the CLOSE_WAIT state when I stop one of the processes kafka.

Correct, but connection should always be closed. Broker is closing all connection when closing, so does [muCloseDeadConnection](https://github.com/optiopay/kafka/blob/master/broker.go#L442-L462).

Can you be more specific where connection may hang?

**Comment by legionus** [comment]
Yes. You are right.

**Comment by husio** [comment]
Cool. Then I'm closing this pull request.

**Pull request closed without merging**
