### PR TITLE
Close dead connections in broker.offset

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by dmage** [comment]
There is something weird that the library returns an error whose cause has been eliminated. This is shown in the test in the form of a check for EOF.

**Comment by husio** [comment]
You're right that returning error that was half handled is stange and maybe it should be refactored. It's not that easy though, because retry and error handling is taking care of differently, depending on what connection was used for.

**Comment by husio** [comment]
Code looks good, but the tests fail on tip go version. Not yet sure what's the cause of it.

**Comment by optiopay-helper** [comment]
Pull request seem to be stale, assigning @taheris as the responsible developer.

**Comment by dmage** [comment]
On tip the error is syscall.ECONNRESET, which does not handled anywhere in the code.

**Comment by husio** [comment]
Now 1.4.2 is also failing :stuck_out_tongue:

**Comment by dmage** [comment]
Yep, thanks to GOMAXPROCS > 1 :)

**Comment by dmage** [comment]
It may be fixed by something like this:
```(diff)
-    if err == io.EOF || err == syscall.EPIPE {
+    if _, ok := err.(*net.OpError); ok || err == io.EOF || err == syscall.EPIPE {
```

**Comment by husio** [comment]
It it pass then it's good for now. I must find some time soon to revisit error handling and clean the code a bit.

**Pull request merged**
