### PR TITLE
Add new options to the fake server

### PR DESCRIPTION
**Pull request by zorkian**
First, this allows you to add a pending error to be returned on produce
requests. This can be used to simulate error conditions and ensure your
client error handling works.

Second, add arbitrary response delay option so you can make the server
simulate latency.

### CODE REVIEW

**Comment by zorkian** [comment]
Are you interested in this kind of functionality? I am testing using this client here and we need to simulate error conditions of various sorts in our unit tests.

**Comment by husio** [comment]
It's a good idea to be able to simulate various scenario with test server. I think there might be a better way to allow for customization. What do you think about using middleware to control request/response cycle? I wrote quick implementation with example that apply delay to all fetch requests https://github.com/optiopay/kafka/compare/master...husio:test_middleware

Would this be sufficient for what you're trying to do?

**Comment by optiopay-helper** [comment]
Pull request seem to be stale, assigning @MikeRoetgers as the responsible developer.

**Comment by zorkian** [comment]
That's a pretty aggressive bot for an open sourced pull request. :)

I think the middleware will do what I want, but I will have to try to port our unit tests over. I am running a single `kafkatest.Server` and using it in our dozen unit tests, so I needed to change its behavior on the fly. That said, it's so easy to tear down/set up that it'd be trivial for me to build one for each test (with its own middleware, possibly).

So -- yes, I think your approach will work, and is a lot more flexible. +1 for that, so I'll close this request.

**Comment by husio** [comment]
Cool, I will still think about it through the weekend and push changes on monday.

Don't worry about the bot.

**Pull request closed without merging**
